## 1.1 Create vector

In [1]:
import numpy as np

In [2]:
row_vec = np.array([1,2,3])

In [3]:
col_vec = np.array([[1],
                   [2],
                   [3]])

In [4]:
row_vec

array([1, 2, 3])

In [5]:
col_vec

array([[1],
       [2],
       [3]])

## 1.2 Create matrix

In [6]:
matrix = np.array([[1,2],
                   [3,4]])

In [7]:
matrix

array([[1, 2],
       [3, 4]])

### Matrix Object

In [8]:
matrix_obj = np.mat([[1,2],
                   [3,4]])

In [9]:
matrix_obj

matrix([[1, 2],
        [3, 4]])

### 1.3 Sparse Matrix

In [13]:
from scipy import sparse

In [12]:
matrix = np.array([[0,0],
                   [3,0],
                  [0,6]])

In [14]:
matrix_sparse = sparse.csr_matrix(matrix)

In [16]:
print(matrix_sparse)

  (1, 0)	3
  (2, 1)	6


In [17]:
matrix_large = np.array([[0,0,0,0,0,0,0,0],
                   [3,0,0,0,0,0,0,0],
                  [0,6,0,0,0,0,0,0]])

In [18]:
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [19]:
print(matrix_large_sparse)

  (1, 0)	3
  (2, 1)	6


## Pre-Allocate Numpy Arrays

### Zero Vector

In [20]:
vector = np.zeros(5)

In [24]:
vector

array([0., 0., 0., 0., 0.])

### Fill matrix with single value

In [22]:
matrix = np.full(shape = (3,3), fill_value = 1)

In [23]:
matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## 1.4 Selecting Elements

In [25]:
vector = np.array([1,2,3,4,5,6])

In [26]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [30]:
vector[2]

3

In [31]:
vector[3:]

array([4, 5, 6])

In [32]:
matrix[1,1]

5

In [33]:
vector[-1]

6

In [34]:
matrix[:,2]

array([3, 6, 9])

In [36]:
vector[-1::-1]

array([6, 5, 4, 3, 2, 1])

In [37]:
vector[1::2]

array([2, 4, 6])

In [38]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

## 1.5 Describing a Matrix

In [43]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

### Shape of Matrix

In [44]:
matrix.shape

(3, 3)

### Size of Matrix

In [45]:
matrix.size

9

### Dimensions of matrix

In [42]:
matrix.ndim

2

##  1.6 Applying Operations over each element

### Numpy's vectorize method

In [46]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

### Lambda function

In [49]:
add_100 = lambda i: i+100

### Create Vectorized function

In [50]:
vectorized_add_100 = np.vectorize(add_100)

### Apply function to all elements in matrix

In [53]:
result = vectorized_add_100(matrix)

In [56]:
result

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

### Alternate approach :  Broadcasting

In [55]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 1.7 Finding max and min

In [57]:
np.max(matrix)

9

In [62]:
np.min(matrix)

1

## 1.8 Calculating the Average, Variance, and Standard Deviation

In [59]:
np.mean(matrix)

5.0

In [60]:
np.var(matrix)

6.666666666666667

In [61]:
np.std(matrix)

2.581988897471611

## 1.9 Reshaping Arrays

In [65]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])

In [66]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [69]:
matrix.reshape(-1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [70]:
matrix.ndim

2

In [71]:
vector.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
vector.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [73]:
vector.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [74]:
vector = np.array([1,2,3,4,5,6,7,8])

In [78]:
vec3d = vector.reshape(2,2,2)

In [83]:
vec3d.ndim

3

## 1.10 Transposing a Vector or Matrix

In [80]:
matrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [81]:
matrix.shape

(4, 3)

In [82]:
matrix.T.shape

(3, 4)

In [84]:
vector = np.array([1,2,3,4,5,6])

In [85]:
vector.T

array([1, 2, 3, 4, 5, 6])

In [86]:
rowVec = np.array([[1,2,3,4,5,6]])

In [87]:
rowVec.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.11 Flattening a Matrix

In [88]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [95]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
type(matrix)

numpy.ndarray

## Alternative to flatten : Ravel
operates on original object, faster

In [98]:
np.ravel(matrix)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
matrix_a = np.array([[1,2],
                   [3,4]])

In [103]:
matrix_b = np.array([[5,6],
                   [7,8]])

In [104]:
matrix_list = [matrix_a, matrix_b]

In [105]:
np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Linear Algebra on Matrices

In [108]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

## 1.12 Finding the Rank of a Matrix

In [109]:
np.linalg.matrix_rank(matrix)

2

## 1.14 Getting the Diagonal of a Matrix

In [112]:
matrix.diagonal()

array([1, 5, 9])

#### Offset Diagonal

In [111]:
matrix.diagonal(offset = 1)

array([2, 6])

## 1.15 Calculating the Trace of a Matrix

In [113]:
matrix.trace()
# Sum of diagonal elements

15

In [114]:
sum(matrix.diagonal())

15

## 1.17 Calculating Dot Products

In [115]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [116]:
np.dot(vector_a, vector_b)

32

In [117]:
vector_a @ vector_b

32

## 1.18 Adding and Subtracting Matrices

In [120]:
matrix_a = np.array([[1,2],
                   [3,4]])

In [121]:
matrix_b = np.array([[5,6],
                   [7,8]])

In [124]:
np.add(matrix_a, matrix_b)

array([[ 6,  8],
       [10, 12]])

In [125]:
matrix_a + matrix_b

array([[ 6,  8],
       [10, 12]])

In [123]:
np.subtract(matrix_a, matrix_b)

array([[-4, -4],
       [-4, -4]])

In [129]:
matrix_a - matrix_b

array([[-4, -4],
       [-4, -4]])

## 1.19 Multiplying Matrices

In [127]:
np.dot(matrix_a, matrix_b)

array([[19, 22],
       [43, 50]])

In [128]:
matrix_a @ matrix_b

array([[19, 22],
       [43, 50]])

## 1.20 Inverting a Matrix

In [131]:
np.linalg.inv(matrix_a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [133]:
matrix_a @ np.linalg.inv(matrix_a)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

## 1.21 Generating Random Values

In [134]:
np.random.seed(0)

In [135]:
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

## Random Integer

In [136]:
np.random.randint(0,11,3)

array([3, 7, 9])

## Random numbers from Normal distribution

In [137]:
np.random.normal(0,1,3)

array([-1.42232584,  1.52006949, -0.29139398])

## Random numbers from logistic distribution

In [138]:
np.random.logistic(0,1,3)

array([-0.98118713, -0.08939902,  1.46416405])

## Random numbers from Uniform distribution

In [ ]:
np.rando